name: PlayTak Server CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "server/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK 21
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests
        working-directory: ./server
        run: mvn -B test

      - name: Run build
        working-directory: ./server
        run: mvn -B package
